// Classic99 v4xx - Copyright 2021 by Mike Brent (HarmlessLion.com)
// See License.txt, but the answer is "just ask me first". ;)

// This class sets up the 99/4 keyboard

#include "kb_994.h"

static Array8x8 KEYS = {  
    // Keyboard - 99/4
    /* unused */	ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE,

    /* 1 */			ALLEGRO_KEY_N, ALLEGRO_KEY_H, ALLEGRO_KEY_U, ALLEGRO_KEY_7, ALLEGRO_KEY_C, ALLEGRO_KEY_D, ALLEGRO_KEY_R, ALLEGRO_KEY_4,
    /* Joy 1 */		ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE,
    /* 3 */			ALLEGRO_KEY_FULLSTOP, ALLEGRO_KEY_K, ALLEGRO_KEY_O, ALLEGRO_KEY_9, ALLEGRO_KEY_Z, ALLEGRO_KEY_A, ALLEGRO_KEY_W, ALLEGRO_KEY_2,

    /* Joy 2 */		ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE, ALLEGRO_KEY_ESCAPE,
	
    /* 5 */			ALLEGRO_KEY_M, ALLEGRO_KEY_J, ALLEGRO_KEY_I, ALLEGRO_KEY_8, ALLEGRO_KEY_X, ALLEGRO_KEY_S, ALLEGRO_KEY_E, ALLEGRO_KEY_3,
    /* 6 */			ALLEGRO_KEY_B, ALLEGRO_KEY_G, ALLEGRO_KEY_Y, ALLEGRO_KEY_6, ALLEGRO_KEY_V, ALLEGRO_KEY_F, ALLEGRO_KEY_T, ALLEGRO_KEY_5,
    /* 7 */			ALLEGRO_KEY_ENTER, ALLEGRO_KEY_L, ALLEGRO_KEY_P, ALLEGRO_KEY_0, ALLEGRO_KEY_LSHIFT, ALLEGRO_KEY_SPACE, ALLEGRO_KEY_Q, ALLEGRO_KEY_1
};

// not much needed for construction
KB994::KB994(Classic99System *core) 
    : TIKeyboard(core)
{
}

KB994::~KB994() {
}

int KB994::getJoy1Col() {
    return 2;
}

int KB994::getJoy2Col() {
    return 4;
}

Array8x8 &KB994::getKeyArray() {
    return KEYS;
}
